name: Validate JSONs

on:
  push:
  
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate scoreboard
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'scoreboard.json'
          schema: '/highscores/scoreboard.schema.json'


          
