name: Validate JSONs

on:
  push:
  
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /highscores/schema.json
          INPUT_JSONS: /highscores/scoreboard.json,


          
